plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.14'
}

group = 'com.antlab'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

javafx {
    version = '21.0.2'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass = 'com.antlab.rigcontrol.App'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

